name: build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18', '20']

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Cache npm dependencies
    - run: npm clean-install
      env:
        FORCE_COLOR: 2
    - name: Run Lint
      run: npm run lint # Add linting step
      env:
        FORCE_COLOR: 2
    - name: Run Build
      run: npm run all
      env:
        FORCE_COLOR: 2
    - name: Run Tests
      run: npm run test
      env:
        FORCE_COLOR: 2
    - name: Upload Coverage
      run: npm run coverage # Add code coverage step
      env:
        FORCE_COLOR: 2

  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Notify on Failure
      if: failure()
      uses: actions/github-script@v3
      with:
        script: |
          const { context } = require('@actions/github');
          const issue = context.issue;
          const message = `Build failed for ${issue.html_url}`;
          console.log(message);
